version: '3'

services:
  payload:
    image: oven/bun:1-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/bun/app
      - node_modules:/home/bun/app/node_modules
      - sqlite_data:/home/bun/app/data
    working_dir: /home/bun/app/
    command: sh -c "bun install && bun dev"
    env_file:
      - .env

volumes:
  node_modules:
  sqlite_data:
